export type Service = { name: string; description: string; image: string; tags: string[] };

export const services: Service[] = [
  { name: 'AI Chatbot', image: '/services/ai-chatbot-preview.png', tags: ['LLM-powered', 'RAG integration', 'Workflow automation'], description: 'Intelligent assistants that answer faster, automate routine work, and give your customers a more useful digital experience.' },
  { name: 'Web Development', image: '/services/web-development-preview.png', tags: ['Fast builds', 'Scalable systems', 'SEO-ready'], description: 'Modern web platforms engineered to load quickly, scale confidently, and turn your digital presence into measurable growth.' },
  { name: 'ERP', image: '/services/erp-preview.png', tags: ['Business workflows', 'Custom dashboards', 'Connected data'], description: 'Purpose-built ERP systems that bring operations, reporting, and decision-making into one clear, dependable workspace.' },
  { name: 'Mobile App', image: '/services/mobile-app-preview.png', tags: ['iOS & Android', 'Product strategy', 'App store ready'], description: 'Useful mobile products with thoughtful flows, reliable performance, and a clear path from first tap to loyal customer.' },
  { name: 'WordPress Development', image: '/services/wordpress-preview.png', tags: ['Custom themes', 'Easy publishing', 'Secure foundation'], description: 'Flexible WordPress experiences that give your team control without compromising on speed, quality, or visual polish.' },
  { name: 'Graphic Design', image: '/services/graphic-design-preview.png', tags: ['Brand assets', 'Campaign creative', 'Clear storytelling'], description: 'Visual systems and campaign materials that make your brand recognisable, clear, and ready for every touchpoint.' },
  { name: 'Ads Video Editing', image: '/services/ads-video-editing-preview.png', tags: ['Short-form video', 'Paid campaigns', 'Social-ready'], description: 'Attention-holding ad edits built to communicate quickly, fit each platform, and move audiences toward action.' },
  { name: 'PC Related Issues', image: '/services/pc-support-preview.png', tags: ['Troubleshooting', 'Performance tuning', 'Remote support'], description: 'Straightforward technical support that resolves PC issues, restores performance, and keeps your team moving.' },
  { name: 'RDP', image: '/services/rdp-preview.png', tags: ['Secure access', 'Remote teams', 'Reliable setup'], description: 'Remote desktop environments configured for secure, dependable access wherever your team needs to work.' },
  { name: 'Windows Server Management', image: '/services/windows-server-preview.png', tags: ['Server setup', 'Monitoring', 'Ongoing support'], description: 'Windows Server management that keeps your infrastructure stable, secure, and ready for the demands of your business.' },
];
